### ISSUE TITLE
Error when converting factor to numeric in formula

### ISSUE THREAD

**Issue by hack-r** [leeper/margins#38]
```
hsbdemo <- read.csv("http://www.ats.ucla.edu/stat/data/hsbdemo.csv")
logit1  <- glm("honors ~ I(-1*I(female=='female')) + I(-1*read)", data = hsbdemo, family="binomial")
summary(logit1) # model looks good

marginal_effects(logit1)

```

> 
> Error in `[[<-.data.frame`(`*tmp*`, variable, value = numeric(0)) : 
>   replacement has 0 rows, data has 200

**Comment by leeper** [comment]
Thanks. I'm guessing it's something about the nested `I(I())`. Does it work if you drop the inner `I()`?

**Comment by leeper** [comment]
Okay the issue is basically [here](https://github.com/leeper/margins/blob/master/R/marginal_effects.R#L37-L42). With `I()` expressions, the code isn't finding the right variables. So, this should probably make a call to `all.vars(terms(model))` to find the right variable names.

(But it might be little complicated to map that to the classes of each variable.)

**Comment by leeper** [comment]
This is an interesting problem. Transforming a factor variable into a numeric using `I()` makes the `female` variable a bit hard to work with because the model object doesn't know the original variable was a factor. For the time being I've added a warning for when this occurs, so the function at least executes, though the MEs are returned as `NA`. I'll try to come up with a general solution to this.

**Comment by hack-r** [comment]
Interesting, good luck!
