### ISSUE TITLE
Better handling of weights

### ISSUE THREAD

**Issue by leeper** [leeper/margins#45]
- [x] Issue warning when weights are present about them being ignored
 - [x] Provide options for how to handle
   - Stata discussion is here: http://www.stata.com/manuals13/rmargins.pdf
   - Stata's default is a weighted mean based upon those weights, with an option to `noweight` (ignore weights used in estimation)

**Comment by blechturm** [comment]
Hi, I wonder how to use the margins package with correct weights for my stratified sample (EU-SILC). I tried to duplicate the rows according to their weights (for instance one observation was duplicated 23 times to reflect its weight) and ran my probit model on it. This should give me the correct (representative) point estimates for the coefficients and for the AMEs but the confidence intervalls should be too small since my sample was inflated. Could you give me a hint how it is done correctly?

Sorry if this is the wrong place, I am pretty new to github.
Best,
Max

**Comment by leeper** [comment]
Closed by https://github.com/leeper/margins/commit/73e5a8c24fee67a2d21c20d14e32fd699bc24916
