### ISSUE TITLE
how to obtain correct CIs with robust SEs coming from sandwich?

### ISSUE THREAD

**Issue by randomgambit** [leeper/margins#72]
Hello,

Thanks for this amazing package! I am wondering how to get the correct prediction intervals with `margins`, when one needs robust standard errors (from the `sandwitch` package), say:

```
library(foreign)
library(sandwich)
library(lmtest)

dfAPI = read.dta("http://www.ats.ucla.edu/stat/stata/webbooks/reg/elemapi2.dta")
lmAPI = lm(api00 ~ acs_k3 + acs_46 + full + enroll, data= dfAPI)

# reproduce the Stata robust se
coeftest(lmAPI, vcov = vcovHC(lmAPI, "HC1")) 
```

**Comment by leeper** [comment]
`margins()` has a `vcov` argument that you can use in a fashion similar to that (for marginal effects; there's no support here for predicted values [yet]).

**Comment by randomgambit** [comment]
great, thanks. Do you plan on doing that? I think this is both important and very useful. It also fills a gap in the R landcape (I am not aware of any other package that can do that, are you?)

**Comment by leeper** [comment]
margins uses the prediction package under the hood, and `prediction::prediction()` will give you average predictions (but not their variances because up until now they aren't needed for `margins()` to work). It's an open issue to support them: https://github.com/leeper/prediction/issues/17

I think lsmeans can do some kind of average prediction but it's been a long time since I've played around with it.
